### ISSUE TITLE
Todo: A discussion of possible ehancements

### ISSUE THREAD

**Issue by JossWhittle** [L2Program/FlintPlusPlus#14]
## Tokenizer.cpp

Todo:
- [x] Exchange string copy `pc` for a non-destructive `string::iterator`
- [x] Profile for possible performance bottlenecks during tokenizing

Discuss:
- Is it possible to check for blacklisted identifiers during Tokenization?
## Checks.cpp

Todo:
- [x] NULL vs nullptr check can be combined with Banned Identifiers check
- [x] All checks which use `iterateClasses` could be combined to use a single call to that function
